# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 23:39
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SalesRep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('login_email', models.EmailField(max_length=254, unique=True)),
                ('username', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=254)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='salesrep',
            unique_together=set([('username', 'login_email')]),
        ),
    ]
