# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 01:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160617_0046'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 17, 1, 24, 51, 576510, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 17, 1, 25, 0, 880545, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
