# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 00:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_maingroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='number_of_main_groups',
            field=models.IntegerField(default=0),
        ),
    ]
