# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 05:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_responsibilitytype_service_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('input_type', models.CharField(choices=[('RD', 'radio'), ('TX', 'text'), ('EM', 'email'), ('NM', 'number')], default='TX', max_length=2)),
                ('placeholder', models.CharField(default='', max_length=254)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('required', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='options',
            field=models.ManyToManyField(blank=True, null=True, to='api.ServiceOption'),
        ),
    ]
