# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20160703_0622'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionInputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('input_type', models.CharField(choices=[('RD', 'radio'), ('TX', 'text'), ('EM', 'email'), ('NM', 'number'), ('CB', 'checkbox')], default='TX', max_length=2)),
                ('placeholder', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('required', models.BooleanField(default=False)),
                ('value_one', models.CharField(blank=True, default='', max_length=254, null=True)),
                ('value_two', models.CharField(blank=True, default='', max_length=254, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='serviceoption',
            name='input_type',
        ),
        migrations.RemoveField(
            model_name='serviceoption',
            name='placeholder',
        ),
        migrations.RemoveField(
            model_name='serviceoption',
            name='required',
        ),
        migrations.RemoveField(
            model_name='serviceoption',
            name='values',
        ),
        migrations.AddField(
            model_name='serviceoption',
            name='need_inputs',
            field=models.ManyToManyField(blank=True, null=True, to='api.OptionInputs'),
        ),
    ]
