# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20160703_1427'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OptionInputs',
            new_name='OptionInput',
        ),
    ]
