# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20160703_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='optioninput',
            name='map_required',
            field=models.BooleanField(default=False),
        ),
    ]
