# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_optioninput_map_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optioninput',
            name='map_required',
        ),
        migrations.AddField(
            model_name='serviceoption',
            name='map_required',
            field=models.BooleanField(default=False),
        ),
    ]
