# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20160703_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optioninput',
            name='input_type',
            field=models.CharField(choices=[('RD', 'radio'), ('TX', 'text'), ('EM', 'email'), ('NM', 'number'), ('CB', 'checkbox'), ('HD', 'hidden')], default='TX', max_length=2),
        ),
    ]
