# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-03 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20160703_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceoption',
            old_name='need_inputs',
            new_name='inputs',
        ),
    ]
